### PR TITLE
Changed the database uri to postgresql.

### LINKED ISSUE #9: login, signup, organization and donation routes in the api

### LINKED ISSUE #30: deploy the backend
Deployed it on render as Postgresql service

### PR DESCRIPTION
**Pull request by Noelle-Wavinya-Maingi**
# Description

Changed the database uri to the postgresql uri

## Type of change

{choose an option that applies to what you have done}(use X)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ x ] tested by postman
- [ x ] tested by pytest

# Checklist: (use X to all parts that you have done)

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code
- [ x ] My changes generate no new warnings
- [ x ] I have  tested that  my part is effective or that my feature works
- [ x ] Works locally with my changes

### CODE REVIEW

**Review by Ian32-del — APPROVED** [review]

**Comment by kipngenohaaron** [comment]
updated

**Review by kipngenohaaron — COMMENTED** [review]
Postgresql used

**Review by kipngenohaaron — COMMENTED** [review]
# Description

Changed the database uri to the postgresql uri


## Type of change

{choose an option that applies to what you have done}(use X)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?


- [ x ] tested by postman
- [ x ] tested by pytest



# Checklist: (use X to all parts that you have done)

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code
- [ x ] My changes generate no new warnings
- [ x ] I have  tested that  my part is effective or that my feature works
- [ x ] Works locally with my changes

**Review by kipngenohaaron — COMMENTED** [review]
Good progress

**Pull request merged**
